#include <iostream>
using namespace std;

// Max Heap
void maxHeapify(int a[], int n, int i)
{
    int largest = i;
    int left = 2 * i + 1;
    int right = 2 * i + 2;

    if(left < n && a[left] > a[largest])
        largest = left;

    if(right < n && a[right] > a[largest])
        largest = right;

    if(largest != i)
    {
        swap(a[i], a[largest]);
        maxHeapify(a, n, largest);
    }
}

void maxHeapSort(int a[], int n)
{
    // Build Max Heap
    for(int i = n / 2 - 1; i >= 0; i--)
        maxHeapify(a, n, i);

    // Heap Sort
    for(int i = n - 1; i > 0; i--)
    {
        swap(a[0], a[i]);
        maxHeapify(a, i, 0);
    }
}

// Min Heap
void minHeapify(int a[], int n, int i)
{
    int smallest = i;
    int left = 2 * i + 1;
    int right = 2 * i + 2;

    if(left < n && a[left] < a[smallest])
        smallest = left;

    if(right < n && a[right] < a[smallest])
        smallest = right;

    if(smallest != i)
    {
        swap(a[i], a[smallest]);
        minHeapify(a, n, smallest);
    }
}

void minHeapSort(int a[], int n)
{
    // Build Min Heap
    for(int i = n / 2 - 1; i >= 0; i--)
        minHeapify(a, n, i);

    // Heap Sort
    for(int i = n - 1; i > 0; i--)
    {
        swap(a[0], a[i]);
        minHeapify(a, i, 0);
    }
}

// Display
void display(int a[], int n)
{
    for(int i = 0; i < n; i++)
        cout << a[i] << " ";

    cout << endl;
}

int main()
{
    int a[100], n, choice;

    cout << "Enter number of elements: ";
    cin >> n;

    cout << "Enter elements: ";
    for(int i = 0; i < n; i++)
        cin >> a[i];

    cout << "\n1. Max Heap Sort";
    cout << "\n2. Min Heap Sort";
    cout << "\nEnter choice: ";
    cin >> choice;

    if(choice == 1)
    {
        maxHeapSort(a, n);

        cout << "\nMax Heap Sort: ";
        display(a, n);
    }
    else if(choice == 2)
    {
        minHeapSort(a, n);

        cout << "\nMin Heap Sort: ";
        display(a, n);
    }
    else
    {
        cout << "Wrong choice!";
    }

    return 0;
}
